#!/usr/bin/env python3
import os
import re
import subprocess
import base64
import uuid
from datetime import datetime
from pathlib import Path

# ==========================================
# 輸出路徑 (ASPICE SWE.3 附屬 API 參考文件)
# ==========================================
OUTPUT_BASE = os.path.join("docs", "03_software_detailed_design", "api")
LANGUAGES = ["en", "cn", "tw"]

# ==========================================
# 多語系翻譯字典
# ==========================================
I18N = {
    "en": {
        "project_title": "IRQ Simulator - Auto-Generated API Reference",
        "project_overview": "This is a C language embedded project developed with TRAE IDE, featuring interrupt handling and GitLab CI/CD integration.",
        "total_files_scanned": "Total source files scanned: {total_files}, {total_funcs} function definitions extracted.",
        "doc_generated_time": "Document Generated At",
        "module_arch_diagram": "Module Architecture Diagram",
        "file_path_label": "File Path",
        "no_funcs_found": "No functions with matching Doxygen comments found in this file.",
        "item": "Item",
        "description": "Description",
        "brief_label": "Brief",
        "no_brief": "No description",
        "params_label": "Parameters",
        "none": "None",
        "retval_label": "Return Value",
        "retval_void": "None (void)",
        "remark_label": "Remark",
        "exec_flow": "Execution Flow Diagram",
        "pdf_download": "PDF Download",
        "pdf_desc": "PDF Document (includes full architecture and source code documentation)",
        "pdf_link_text": "Download Complete Documentation (PDF)",
        "auto_generated_footer": "This document is auto-generated by GitLab CI from source code.",
        "nav_home": "Overview",
        "nav_source_structure": "Source Code Structure",
        "toc_title": "Table of Contents",
        "arch_reset_entry": "Reset Entry",
        "arch_main_func": "main Function",
        "arch_reg_handlers": "Register ISR Handlers",
        "arch_main_loop": "Main Loop",
        "arch_tick_isr": "Tick ISR",
        "arch_ext_isr": "External ISR",
        "arch_tick_check": "tick handler set?",
        "arch_int_check": "int handler set?",
        "arch_yes": "Yes",
        "arch_set": "Set",
        "flow_start": "Start",
        "flow_init": "Initialize ISR Pointers",
        "flow_reg_tick": "Set _rom_except_tick",
        "flow_reg_int": "Set _rom_except_int",
        "flow_print": "Print Welcome Message",
        "flow_loop": "Enter Main Loop",
        "flow_tick_trigger": "Tick IRQ Triggered",
        "flow_inc_tick": "Increment tick_count",
        "flow_return": "Return",
        "flow_exc_trigger": "Exception IRQ Triggered",
        "flow_inc_exc": "Increment exception_count",
        "flow_main": "main Execution Flow",
        "flow_tick": "tick_irq_handler Execution Flow",
        "flow_exc": "exception_irq_handler Execution Flow",
        "banner": "TRAE Project Auto-Documentation Generator (ASPICE SWE.3 API Reference)",
        "step_scan": "Searching for all .c and .h files...",
        "step_parse": "Parsing source code and rendering diagrams via mmdc...",
        "step_index": "Generating language-specific index pages and print CSS...",
        "step_mkdocs": "Generating mkdocs.yml...",
        "found_files": "source files found",
        "processed": "Processed",
        "funcs": "functions",
        "done": "Documentation generation complete! Output:",
        "warn_mermaid": "Mermaid conversion failed",
    },
    "cn": {
        "project_title": "IRQ Simulator - 自动生成 API 参考文件",
        "project_overview": "这是一个使用 TRAE IDE 开发的 C 语言嵌入式项目，包含中断处理功能和 GitLab CI/CD 集成。",
        "total_files_scanned": "共扫描 {total_files} 个源代码文件，提取出 {total_funcs} 个函数定义。",
        "doc_generated_time": "文件生成时间",
        "module_arch_diagram": "模块架构图",
        "file_path_label": "文件路径",
        "no_funcs_found": "此文件目前没有解析到符合格式的函数注释。",
        "item": "项目",
        "description": "说明",
        "brief_label": "功能说明",
        "no_brief": "无特别说明",
        "params_label": "参数说明",
        "none": "无",
        "retval_label": "返回值",
        "retval_void": "无 (void)",
        "remark_label": "备注",
        "exec_flow": "执行流程图",
        "pdf_download": "PDF 下载",
        "pdf_desc": "PDF 文件 (包含完整架构与源代码说明)",
        "pdf_link_text": "下载完整说明文件 (PDF)",
        "auto_generated_footer": "本文件由 GitLab CI 自动扫描源代码并生成。",
        "nav_home": "概述",
        "nav_source_structure": "源代码结构",
        "toc_title": "目录",
        "arch_reset_entry": "重置入口",
        "arch_main_func": "main 函数",
        "arch_reg_handlers": "注册中断处理器",
        "arch_main_loop": "主循环",
        "arch_tick_isr": "Tick 中断",
        "arch_ext_isr": "外部中断",
        "arch_tick_check": "tick 处理器已设置?",
        "arch_int_check": "int 处理器已设置?",
        "arch_yes": "是",
        "arch_set": "设置",
        "flow_start": "开始",
        "flow_init": "初始化中断处理器指针",
        "flow_reg_tick": "设置 _rom_except_tick",
        "flow_reg_int": "设置 _rom_except_int",
        "flow_print": "打印欢迎信息",
        "flow_loop": "进入主循环",
        "flow_tick_trigger": "Tick IRQ 触发",
        "flow_inc_tick": "增加 tick_count",
        "flow_return": "返回",
        "flow_exc_trigger": "Exception IRQ 触发",
        "flow_inc_exc": "增加 exception_count",
        "flow_main": "main 执行流程图",
        "flow_tick": "tick_irq_handler 执行流程图",
        "flow_exc": "exception_irq_handler 执行流程图",
        "banner": "TRAE 项目自动文档生成器 (ASPICE SWE.3 API 参考)",
        "step_scan": "正在搜索所有 .c 和 .h 文件...",
        "step_parse": "正在解析源代码并调用 mmdc 渲染图表...",
        "step_index": "正在生成各语言首页与打印 CSS...",
        "step_mkdocs": "正在生成 mkdocs.yml...",
        "found_files": "个源代码文件",
        "processed": "处理完成",
        "funcs": "个函数",
        "done": "文档生成完成！输出目录：",
        "warn_mermaid": "Mermaid 转换失败",
    },
    "tw": {
        "project_title": "IRQ Simulator - 自動生成 API 參考文件",
        "project_overview": "這是一個使用 TRAE IDE 開發的 C 語言嵌入式專案，包含中斷處理功能和 GitLab CI/CD 整合。",
        "total_files_scanned": "總共掃描到 {total_files} 個原始碼檔案，擷取出 {total_funcs} 個函式定義。",
        "doc_generated_time": "文件產生時間",
        "module_arch_diagram": "模組架構圖",
        "file_path_label": "檔案路徑",
        "no_funcs_found": "此檔案目前沒有解析到符合格式的函式註解。",
        "item": "項目",
        "description": "說明",
        "brief_label": "功能說明",
        "no_brief": "無特別說明",
        "params_label": "參數說明",
        "none": "無",
        "retval_label": "回傳值",
        "retval_void": "無 (void)",
        "remark_label": "備註",
        "exec_flow": "執行流程圖",
        "pdf_download": "PDF 下載",
        "pdf_desc": "PDF 文件 (包含完整架構與原始碼說明)",
        "pdf_link_text": "下載完整說明文件 (PDF)",
        "auto_generated_footer": "本文件由 GitLab CI 自動掃描原始碼並產生。",
        "nav_home": "概述",
        "nav_source_structure": "原始碼結構",
        "toc_title": "目錄",
        "arch_reset_entry": "重置入口",
        "arch_main_func": "main 函式",
        "arch_reg_handlers": "註冊中斷處理器",
        "arch_main_loop": "主迴圈",
        "arch_tick_isr": "Tick 中斷",
        "arch_ext_isr": "外部中斷",
        "arch_tick_check": "tick 處理器已設定?",
        "arch_int_check": "int 處理器已設定?",
        "arch_yes": "是",
        "arch_set": "設定",
        "flow_start": "開始",
        "flow_init": "初始化中斷處理器指標",
        "flow_reg_tick": "設定 _rom_except_tick",
        "flow_reg_int": "設定 _rom_except_int",
        "flow_print": "列印歡迎訊息",
        "flow_loop": "進入主迴圈",
        "flow_tick_trigger": "Tick IRQ 觸發",
        "flow_inc_tick": "增加 tick_count",
        "flow_return": "返回",
        "flow_exc_trigger": "Exception IRQ 觸發",
        "flow_inc_exc": "增加 exception_count",
        "flow_main": "main 執行流程圖",
        "flow_tick": "tick_irq_handler 執行流程圖",
        "flow_exc": "exception_irq_handler 執行流程圖",
        "banner": "TRAE 專案自動文件產生器 (ASPICE SWE.3 API 參考)",
        "step_scan": "正在搜尋所有 .c 和 .h 檔案...",
        "step_parse": "正在解析原始碼並呼叫 mmdc 渲染圖表...",
        "step_index": "正在產生各語言首頁與列印 CSS...",
        "step_mkdocs": "正在產生 mkdocs.yml...",
        "found_files": "個原始碼檔案",
        "processed": "處理完成",
        "funcs": "個函式",
        "done": "文件產生完成！輸出目錄：",
        "warn_mermaid": "Mermaid 轉換失敗",
    },
}

# ==========================================
# Mermaid 轉換核心引擎 (PNG 轉 Base64)
# ==========================================
def create_puppeteer_config():
    config_path = "puppeteer-config.json"
    if not os.path.exists(config_path):
        with open(config_path, "w", encoding="utf-8") as f:
            f.write('{"args": ["--no-sandbox", "--disable-setuid-sandbox"]}')
    return config_path

def render_mermaid_to_png_base64(mermaid_code, alt_text, lang="tw"):
    config_path = create_puppeteer_config()
    unique_id = uuid.uuid4().hex
    temp_mmd = f"temp_{unique_id}.mmd"
    temp_png = f"temp_{unique_id}.png"

    with open(temp_mmd, "w", encoding="utf-8") as f:
        f.write(mermaid_code)

    try:
        subprocess.run([
            "mmdc",
            "-i", temp_mmd,
            "-o", temp_png,
            "-p", config_path,
            "-b", "white",
            "-s", "2"
        ], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        with open(temp_png, "rb") as f:
            encoded = base64.b64encode(f.read()).decode('utf-8')

        return f"![{alt_text}](data:image/png;base64,{encoded})"
    except subprocess.CalledProcessError as e:
        t = I18N.get(lang, I18N["tw"])
        print(f"      [{t['warn_mermaid']}]: {e.stderr.decode('utf-8', errors='ignore')}")
        return f"""```mermaid
{mermaid_code}
```"""
    finally:
        if os.path.exists(temp_mmd):
            os.remove(temp_mmd)
        if os.path.exists(temp_png):
            os.remove(temp_png)

# ==========================================
# 專案原始碼解析
# ==========================================
def find_all_source_files():
    source_files = []
    for filepath in Path(".").rglob("*.[ch]"):
        path_str = str(filepath)
        if "build" not in path_str and "docs" not in path_str:
            source_files.append(path_str)
    return sorted(source_files)

def parse_file(filepath):
    if not os.path.exists(filepath):
        return []

    funcs = []
    in_comment = False
    current_comment = []

    with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    for i, line in enumerate(lines):
        if "/**" in line:
            in_comment = True
            current_comment = []
            continue

        if in_comment:
            if "*/" in line:
                in_comment = False
                continue
            current_comment.append(line.strip())
            continue

        func_pattern = r"^(?:(?:void|int|char|unsigned|short|long|static|inline)\s+)+(\w+)\s*\((.*?)\)"
        func_match = re.match(func_pattern, line.strip())

        if func_match and current_comment:
            func_name = func_match.group(1)
            func_params = func_match.group(2)

            brief = ""
            remark = ""
            params = []
            retval = ""

            for cline in current_comment:
                if "@brief" in cline:
                    brief = cline.split("@brief", 1)[1].strip(" :")
                if "@remark" in cline:
                    remark = cline.split("@remark", 1)[1].strip()
                if "@param" in cline:
                    params.append(cline.strip())
                if "@retval" in cline:
                    retval = cline.strip()

            funcs.append({
                "name": func_name,
                "brief": brief,
                "remark": remark,
                "doc_params": params,
                "doc_retval": retval
            })
            current_comment = []

    return funcs

# ==========================================
# 多語系 Markdown 與圖表生成
# ==========================================
def generate_mermaid_arch(lang):
    t = I18N[lang]
    code = f"""graph TD
    A[start.s<br/>{t['arch_reset_entry']}] --> B[_except_reset]
    B --> C[main.c<br/>{t['arch_main_func']}]
    C --> D[{t['arch_reg_handlers']}]
    D --> E[{t['arch_main_loop']}]

    F[_tick_isr<br/>{t['arch_tick_isr']}] --> G{{{t['arch_tick_check']}}}
    G -->|{t['arch_yes']}| H[tick_irq_handler]

    I[_int_isr<br/>{t['arch_ext_isr']}] --> J{{{t['arch_int_check']}}}
    J -->|{t['arch_yes']}| K[exception_irq_handler]

    C -.->|{t['arch_set']}| G
    C -.->|{t['arch_set']}| J
"""
    return render_mermaid_to_png_base64(code, t['module_arch_diagram'], lang)

def generate_function_flow_diagram(func_name, lang):
    t = I18N[lang]
    diagrams = {
        "main": (
            f"""flowchart TD
    Start([{t['flow_start']}]) --> Init[{t['flow_init']}]
    Init --> RegTick[{t['flow_reg_tick']}]
    RegTick --> RegInt[{t['flow_reg_int']}]
    RegInt --> Print1[{t['flow_print']}]
    Print1 --> Loop[{t['flow_loop']}]
    Loop --> Loop
""",
            t['flow_main']
        ),
        "tick_irq_handler": (
            f"""flowchart TD
    Start([{t['flow_tick_trigger']}]) --> Inc[{t['flow_inc_tick']}]
    Inc --> End([{t['flow_return']}])
""",
            t['flow_tick']
        ),
        "exception_irq_handler": (
            f"""flowchart TD
    Start([{t['flow_exc_trigger']}]) --> Inc[{t['flow_inc_exc']}]
    Inc --> End([{t['flow_return']}])
""",
            t['flow_exc']
        ),
    }

    if func_name not in diagrams:
        return ""

    code, alt = diagrams[func_name]
    return render_mermaid_to_png_base64(code, alt, lang)

def generate_index_md(total_files, total_funcs, lang):
    t = I18N[lang]
    content = f"""# {t['project_title']}

**{t['doc_generated_time']}**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## {t['nav_home']}

{t['project_overview']}
{t['total_files_scanned'].format(total_files=total_files, total_funcs=total_funcs)}

---

## {t['module_arch_diagram']}

{generate_mermaid_arch(lang)}

---

<div class="no-print">
<h2>{t['pdf_download']}</h2>
<h3>📄 {t['pdf_desc']}</h3>
<p><a href="../../trae_test_documentation.pdf">📥 {t['pdf_link_text']}</a></p>
<hr>
</div>

*{t['auto_generated_footer']}*
"""
    return content

def generate_file_md(filepath, funcs, lang):
    t = I18N[lang]
    safe_name = filepath.replace("\\", "/").replace(".", "_")
    md_filename = f"{safe_name}_{lang}.md"
    md_full_path = os.path.join(OUTPUT_BASE, md_filename)
    os.makedirs(os.path.dirname(md_full_path), exist_ok=True)

    filename = os.path.basename(filepath)
    is_header_file = filepath.lower().endswith(".h")

    content = f"# {filename}\n\n**{t['file_path_label']}**: `{filepath}`\n\n---\n\n"

    if not funcs:
        content += f"> *{t['no_funcs_found']}*\n"
        return content, md_full_path, md_filename

    for f in funcs:
        content += "\n<div class=\"page-break\"></div>\n\n"
        content += f"### {f['name']}\n\n"

        content += f"| {t['item']} | {t['description']} |\n"
        content += "| :--- | :--- |\n"

        brief_text = f['brief'] if f['brief'] else t['no_brief']
        content += f"| **{t['brief_label']}** | {brief_text} |\n"

        if f['doc_params']:
            params_html = "<br>".join([f"• {p}" for p in f['doc_params']])
            content += f"| **{t['params_label']}** | {params_html} |\n"
        else:
            content += f"| **{t['params_label']}** | {t['none']} |\n"

        if f['doc_retval']:
            content += f"| **{t['retval_label']}** | {f['doc_retval']} |\n"
        else:
            content += f"| **{t['retval_label']}** | {t['retval_void']} |\n"

        if f['remark']:
            content += f"| **{t['remark_label']}** | {f['remark']} |\n"

        content += "\n\n"

        if not is_header_file:
            flow_diag = generate_function_flow_diagram(f['name'], lang)
            if flow_diag:
                content += f"**{t['exec_flow']}**:\n\n"
                content += flow_diag + "\n\n"

        content += "---\n\n"

    return content, md_full_path, md_filename

# ==========================================
# 語系切換首頁 (index.html)
# ==========================================
# ==========================================
# 主首頁 (docs/index.html) — 固定頂欄 + 右側語系下拉，預設英文
# ==========================================
def generate_main_index_html():
    # 預先讀取三個語系的 index markdown 內容
    index_contents = {}
    for lang in LANGUAGES:
        md_path = os.path.join("docs", f"index_{lang}.md")
        if os.path.exists(md_path):
            with open(md_path, "r", encoding="utf-8") as f:
                raw = f.read()
                escaped = raw.replace("\\", "\\\\").replace("`", "\\`").replace("$", "\\$")
                index_contents[lang] = escaped
        else:
            index_contents[lang] = f"# Missing\\n\\nFile `index_{lang}.md` not found."

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IRQ Simulator - Documentation</title>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <style>
        :root {{
            --bg: #f5f5f5;
            --card-bg: #ffffff;
            --text: #333333;
            --text-secondary: #666666;
            --border: #e0e0e0;
            --accent: #4A90D9;
            --code-bg: #f0f0f0;
            --table-stripe: #f9f9f9;
            --shadow: 0 2px 8px rgba(0,0,0,0.08);
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans TC", "Microsoft JhengHei", sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.7;
            min-height: 100vh;
        }}

        .topbar {{
            position: fixed;
            top: 0; left: 0; right: 0;
            z-index: 1000;
            background: var(--card-bg);
            border-bottom: 1px solid var(--border);
            box-shadow: var(--shadow);
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 0 24px;
            height: 52px;
        }}
        .topbar .brand {{
            font-weight: 700;
            font-size: 16px;
            color: #222;
            white-space: nowrap;
        }}
        .topbar .lang-wrap {{
            display: flex;
            align-items: center;
            gap: 8px;
        }}
        .topbar .lang-wrap label {{
            font-size: 13px;
            color: var(--text-secondary);
            white-space: nowrap;
        }}
        .topbar .lang-wrap select {{
            padding: 6px 32px 6px 12px;
            border: 1px solid var(--border);
            border-radius: 6px;
            font-size: 14px;
            color: var(--text);
            background: var(--card-bg);
            cursor: pointer;
            appearance: none;
            -webkit-appearance: none;
            background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23666' stroke-width='2'%3E%3Cpath d='M6 9l6 6 6-6'/%3E%3C/svg%3E");
            background-repeat: no-repeat;
            background-position: right 10px center;
        }}
        .topbar .lang-wrap select:focus {{
            outline: none;
            border-color: var(--accent);
            box-shadow: 0 0 0 2px rgba(74,144,217,0.2);
        }}

        .container {{
            max-width: 960px;
            margin: 0 auto;
            padding: 80px 24px 64px;
        }}
        #content {{
            background: var(--card-bg);
            border-radius: 8px;
            padding: 40px 48px;
            box-shadow: var(--shadow);
            min-height: 400px;
        }}

        #content h1 {{ font-size: 28px; border-bottom: 2px solid var(--accent); padding-bottom: 12px; margin-bottom: 20px; color: #222; }}
        #content h2 {{ font-size: 22px; margin-top: 36px; margin-bottom: 16px; color: #333; border-bottom: 1px solid var(--border); padding-bottom: 8px; }}
        #content h3 {{ font-size: 18px; margin-top: 28px; margin-bottom: 12px; color: #444; }}
        #content p {{ margin-bottom: 14px; }}
        #content strong {{ color: #222; }}
        #content a {{ color: var(--accent); text-decoration: none; }}
        #content a:hover {{ text-decoration: underline; }}
        #content code {{ background: var(--code-bg); padding: 2px 6px; border-radius: 3px; font-family: "SF Mono", "Fira Code", "Consolas", monospace; font-size: 13px; }}
        #content pre {{ background: #2d2d2d; color: #f8f8f2; padding: 16px 20px; border-radius: 6px; overflow-x: auto; margin: 16px 0; font-size: 13px; line-height: 1.5; }}
        #content pre code {{ background: none; padding: 0; color: inherit; }}
        #content table {{ width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 14px; }}
        #content th, #content td {{ border: 1px solid var(--border); padding: 10px 14px; text-align: left; }}
        #content th {{ background: #f0f5fb; font-weight: 600; color: #333; }}
        #content tr:nth-child(even) td {{ background: var(--table-stripe); }}
        #content img {{ max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 4px; }}
        #content hr {{ border: none; border-top: 1px solid var(--border); margin: 28px 0; }}
        #content blockquote {{ border-left: 4px solid var(--accent); padding: 8px 16px; margin: 16px 0; background: #f8fafc; color: var(--text-secondary); border-radius: 0 4px 4px 0; }}
        #content ul, #content ol {{ margin: 12px 0 12px 24px; }}
        #content li {{ margin-bottom: 6px; }}

        .footer {{ text-align: center; padding: 20px; color: #999; font-size: 12px; }}

        @media (max-width: 768px) {{
            .topbar {{ padding: 0 12px; }}
            .topbar .brand {{ font-size: 14px; }}
            .topbar .lang-wrap label {{ display: none; }}
            #content {{ padding: 24px 20px; }}
            .container {{ padding: 72px 12px 40px; }}
        }}
    </style>
</head>
<body>

<div class="topbar">
    <span class="brand">IRQ Simulator Documentation</span>
    <div class="lang-wrap">
        <label for="langSelect">Language:</label>
        <select id="langSelect" onchange="switchLang(this.value)">
            <option value="en" selected>English</option>
            <option value="cn">Simplified Chinese (简体中文)</option>
            <option value="tw">Traditional Chinese (繁體中文)</option>
        </select>
    </div>
</div>

<div class="container">
    <div id="content"></div>
</div>

<div class="footer">
    Auto-generated by GitLab CI &mdash; ASPICE Software Development Documentation
</div>

<script>
    var CONTENTS = {{
        en: `{index_contents['en']}`,
        cn: `{index_contents['cn']}`,
        tw: `{index_contents['tw']}`
    }};
    var LANG_LABELS = {{ en: 'English', cn: 'Simplified Chinese', tw: 'Traditional Chinese' }};
    var currentLang = 'en';

    function switchLang(lang) {{
        if (lang === currentLang) return;
        currentLang = lang;
        document.getElementById('langSelect').value = lang;
        document.title = 'IRQ Simulator - Documentation (' + LANG_LABELS[lang] + ')';
        renderContent(lang);
    }}

    function renderContent(lang) {{
        marked.setOptions({{ breaks: false, gfm: true }});
        document.getElementById('content').innerHTML = marked.parse(CONTENTS[lang]);
    }}

    function init() {{
        var detected = 'en';
        var navLang = (navigator.language || navigator.userLanguage || '').toLowerCase();
        if (navLang.indexOf('zh-tw') === 0 || navLang.indexOf('zh-hk') === 0) detected = 'tw';
        else if (navLang.indexOf('zh-cn') === 0 || navLang.indexOf('zh-sg') === 0) detected = 'cn';
        else if (navLang.indexOf('zh') === 0) detected = 'tw';

        currentLang = detected;
        document.getElementById('langSelect').value = detected;
        document.title = 'IRQ Simulator - Documentation (' + LANG_LABELS[detected] + ')';
        renderContent(detected);
    }}

    document.addEventListener('DOMContentLoaded', init);
</script>

</body>
</html>"""
    html_path = os.path.join("docs", "index.html")
    with open(html_path, "w", encoding="utf-8-sig") as f:
        f.write(html_content)
    return html_path

# ==========================================
# API 細節首頁 (software_design_detail_{lang}.html)
# 嵌入 index_{lang}.md 內容，含架構圖 + 檔案列表 + 連結到各程式碼流程細節文檔
# ==========================================
def generate_api_detail_html(lang):
    t = I18N[lang]
    index_md_path = os.path.join(OUTPUT_BASE, f"api_{lang}.md")

    markdown_content = ""
    if os.path.exists(index_md_path):
        with open(index_md_path, "r", encoding="utf-8") as f:
            markdown_content = f.read()

    escaped_md = markdown_content.replace("\\", "\\\\").replace("`", "\\`").replace("$", "\\$")

    lang_labels = {"en": "English", "cn": "Simplified Chinese", "tw": "Traditional Chinese"}
    lang_label = lang_labels.get(lang, lang)

    html_content = f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{t['project_title']}</title>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <style>
        :root {{
            --bg: #f5f5f5;
            --card-bg: #ffffff;
            --text: #333333;
            --text-secondary: #666666;
            --border: #e0e0e0;
            --accent: #4A90D9;
            --code-bg: #f0f0f0;
            --table-stripe: #f9f9f9;
            --shadow: 0 2px 8px rgba(0,0,0,0.08);
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans TC", "Microsoft JhengHei", sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.7;
            min-height: 100vh;
        }}

        .topbar {{
            position: sticky;
            top: 0;
            z-index: 100;
            background: var(--card-bg);
            border-bottom: 1px solid var(--border);
            box-shadow: var(--shadow);
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 0 24px;
            height: 48px;
        }}
        .topbar .brand {{
            font-weight: 700;
            font-size: 15px;
            color: #222;
        }}
        .topbar .lang-badge {{
            font-size: 12px;
            color: var(--text-secondary);
            background: #f0f0f0;
            padding: 4px 12px;
            border-radius: 12px;
        }}
        .topbar a {{
            color: var(--accent);
            text-decoration: none;
            font-size: 13px;
        }}
        .topbar a:hover {{ text-decoration: underline; }}

        .container {{
            max-width: 960px;
            margin: 0 auto;
            padding: 32px 24px 64px;
        }}
        #content {{
            background: var(--card-bg);
            border-radius: 8px;
            padding: 40px 48px;
            box-shadow: var(--shadow);
            min-height: 400px;
        }}

        #content h1 {{ font-size: 28px; border-bottom: 2px solid var(--accent); padding-bottom: 12px; margin-bottom: 20px; color: #222; }}
        #content h2 {{ font-size: 22px; margin-top: 36px; margin-bottom: 16px; color: #333; border-bottom: 1px solid var(--border); padding-bottom: 8px; }}
        #content h3 {{ font-size: 18px; margin-top: 28px; margin-bottom: 12px; color: #444; }}
        #content p {{ margin-bottom: 14px; }}
        #content strong {{ color: #222; }}
        #content a {{ color: var(--accent); text-decoration: none; }}
        #content a:hover {{ text-decoration: underline; }}
        #content code {{ background: var(--code-bg); padding: 2px 6px; border-radius: 3px; font-family: "SF Mono", "Fira Code", "Consolas", monospace; font-size: 13px; }}
        #content pre {{ background: #2d2d2d; color: #f8f8f2; padding: 16px 20px; border-radius: 6px; overflow-x: auto; margin: 16px 0; font-size: 13px; line-height: 1.5; }}
        #content pre code {{ background: none; padding: 0; color: inherit; }}
        #content table {{ width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 14px; }}
        #content th, #content td {{ border: 1px solid var(--border); padding: 10px 14px; text-align: left; }}
        #content th {{ background: #f0f5fb; font-weight: 600; color: #333; }}
        #content tr:nth-child(even) td {{ background: var(--table-stripe); }}
        #content img {{ max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 4px; }}
        #content hr {{ border: none; border-top: 1px solid var(--border); margin: 28px 0; }}
        #content blockquote {{ border-left: 4px solid var(--accent); padding: 8px 16px; margin: 16px 0; background: #f8fafc; color: var(--text-secondary); border-radius: 0 4px 4px 0; }}
        #content ul, #content ol {{ margin: 12px 0 12px 24px; }}
        #content li {{ margin-bottom: 6px; }}

        .footer {{ text-align: center; padding: 20px; color: #999; font-size: 12px; }}

        @media (max-width: 768px) {{
            .topbar {{ padding: 0 12px; }}
            #content {{ padding: 24px 20px; }}
            .container {{ padding: 16px 12px 40px; }}
        }}
    </style>
</head>
<body>

<div class="topbar">
    <span class="brand">{t['project_title']}</span>
    <div style="display:flex;align-items:center;gap:16px;">
        <a href="../../index.html">&larr; Back to Home</a>
        <span class="lang-badge">{lang_label}</span>
    </div>
</div>

<div class="container">
    <div id="content"></div>
</div>

<div class="footer">
    Auto-generated by GitLab CI &mdash; ASPICE SWE.3 API Reference ({lang_label})
</div>

<script>
    var MARKDOWN_CONTENT = `{escaped_md}`;
    document.addEventListener('DOMContentLoaded', function() {{
        marked.setOptions({{ breaks: false, gfm: true }});
        document.getElementById('content').innerHTML = marked.parse(MARKDOWN_CONTENT);
    }});
</script>

</body>
</html>"""
    html_path = os.path.join(OUTPUT_BASE, f"software_design_detail_{lang}.html")
    with open(html_path, "w", encoding="utf-8-sig") as f:
        f.write(html_content)
    return html_path

# ==========================================
# 通用 Markdown → HTML 轉換器
# 將任意 docs/ 下的 .md 轉為自給自足的 .html（內嵌內容，不需 XHR）
# ==========================================
def generate_page_html(md_content, lang, rel_path, filename):
    t = I18N[lang]

    escaped_md = md_content.replace("\\", "\\\\").replace("`", "\\`").replace("$", "\\$")

    if rel_path == ".":
        home_link = "index.html"
    else:
        depth = rel_path.count(os.sep) + 1
        home_link = ("../" * depth) + "index.html"

    lang_labels = {"en": "English", "cn": "Simplified Chinese", "tw": "Traditional Chinese"}
    lang_label = lang_labels.get(lang, lang)

    title = filename.replace(f"_{lang}.md", "").replace("_", " ").title()
    first_heading = re.search(r'^#\s+(.+)$', md_content, re.MULTILINE)
    if first_heading:
        title = first_heading.group(1).strip()

    html = f"""<!DOCTYPE html>
<html lang="{lang}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
    <style>
        :root {{
            --bg: #f5f5f5;
            --card-bg: #ffffff;
            --text: #333333;
            --text-secondary: #666666;
            --border: #e0e0e0;
            --accent: #4A90D9;
            --code-bg: #f0f0f0;
            --table-stripe: #f9f9f9;
            --shadow: 0 2px 8px rgba(0,0,0,0.08);
        }}
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans TC", "Microsoft JhengHei", sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.7;
            min-height: 100vh;
        }}
        .topbar {{
            position: sticky;
            top: 0;
            z-index: 100;
            background: var(--card-bg);
            border-bottom: 1px solid var(--border);
            box-shadow: var(--shadow);
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 0 24px;
            height: 48px;
        }}
        .topbar .brand {{
            font-weight: 700;
            font-size: 15px;
            color: #222;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            max-width: 60%;
        }}
        .topbar .nav-right {{
            display: flex;
            align-items: center;
            gap: 16px;
            flex-shrink: 0;
        }}
        .topbar a {{
            color: var(--accent);
            text-decoration: none;
            font-size: 13px;
            white-space: nowrap;
        }}
        .topbar a:hover {{ text-decoration: underline; }}
        .lang-badge {{
            font-size: 12px;
            color: var(--text-secondary);
            background: #f0f0f0;
            padding: 4px 12px;
            border-radius: 12px;
            white-space: nowrap;
        }}
        .container {{
            max-width: 960px;
            margin: 0 auto;
            padding: 32px 24px 64px;
        }}
        #content {{
            background: var(--card-bg);
            border-radius: 8px;
            padding: 40px 48px;
            box-shadow: var(--shadow);
            min-height: 400px;
        }}
        #content h1 {{ font-size: 28px; border-bottom: 2px solid var(--accent); padding-bottom: 12px; margin-bottom: 20px; color: #222; }}
        #content h2 {{ font-size: 22px; margin-top: 36px; margin-bottom: 16px; color: #333; border-bottom: 1px solid var(--border); padding-bottom: 8px; }}
        #content h3 {{ font-size: 18px; margin-top: 28px; margin-bottom: 12px; color: #444; }}
        #content p {{ margin-bottom: 14px; }}
        #content strong {{ color: #222; }}
        #content a {{ color: var(--accent); text-decoration: none; }}
        #content a:hover {{ text-decoration: underline; }}
        #content code {{ background: var(--code-bg); padding: 2px 6px; border-radius: 3px; font-family: "SF Mono", "Fira Code", "Consolas", monospace; font-size: 13px; }}
        #content pre {{ background: #2d2d2d; color: #f8f8f2; padding: 16px 20px; border-radius: 6px; overflow-x: auto; margin: 16px 0; font-size: 13px; line-height: 1.5; }}
        #content pre code {{ background: none; padding: 0; color: inherit; }}
        #content table {{ width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 14px; }}
        #content th, #content td {{ border: 1px solid var(--border); padding: 10px 14px; text-align: left; }}
        #content th {{ background: #f0f5fb; font-weight: 600; color: #333; }}
        #content tr:nth-child(even) td {{ background: var(--table-stripe); }}
        #content img {{ max-width: 100%; height: auto; display: block; margin: 16px auto; border-radius: 4px; }}
        #content hr {{ border: none; border-top: 1px solid var(--border); margin: 28px 0; }}
        #content blockquote {{ border-left: 4px solid var(--accent); padding: 8px 16px; margin: 16px 0; background: #f8fafc; color: var(--text-secondary); border-radius: 0 4px 4px 0; }}
        #content ul, #content ol {{ margin: 12px 0 12px 24px; }}
        #content li {{ margin-bottom: 6px; }}
        .footer {{ text-align: center; padding: 20px; color: #999; font-size: 12px; }}
        @media (max-width: 768px) {{
            .topbar {{ padding: 0 12px; }}
            .topbar .brand {{ font-size: 13px; max-width: 50%; }}
            #content {{ padding: 24px 20px; }}
            .container {{ padding: 16px 12px 40px; }}
        }}
    </style>
</head>
<body>

<div class="topbar">
    <span class="brand">{title}</span>
    <div class="nav-right">
        <a href="{home_link}">&larr; Back to Home</a>
        <span class="lang-badge">{lang_label}</span>
    </div>
</div>

<div class="container">
    <div id="content"></div>
</div>

<div class="footer">
    Auto-generated by GitLab CI &mdash; ASPICE Documentation
</div>

<script>
    var MD = `{escaped_md}`;
    document.addEventListener('DOMContentLoaded', function() {{
        marked.setOptions({{ breaks: false, gfm: true }});
        document.getElementById('content').innerHTML = marked.parse(MD);
    }});
</script>

</body>
</html>"""
    return html


def convert_all_md_to_html():
    """掃描 docs/ 下所有 *_xx.md，轉換為自給自足的 HTML"""
    docs_dir = "docs"
    converted = []

    for root, dirs, files in os.walk(docs_dir):
        for f in files:
            if not f.endswith(".md"):
                continue

            lang = None
            for l in LANGUAGES:
                if f.endswith(f"_{l}.md"):
                    lang = l
                    break

            if lang is None:
                continue

            md_path = os.path.join(root, f)
            rel_path = os.path.relpath(root, docs_dir)

            with open(md_path, "r", encoding="utf-8") as mf:
                md_content = mf.read()

            html_name = f.replace(".md", ".html")
            html_path = os.path.join(root, html_name)

            html_content = generate_page_html(md_content, lang, rel_path, f)

            with open(html_path, "w", encoding="utf-8-sig") as hf:
                hf.write(html_content)

            converted.append(html_path)

    return converted

# ==========================================
# 主程式
# ==========================================
def main():
    t_default = I18N["tw"]
    print("=" * 60)
    print(t_default['banner'])
    print("=" * 60)

    print(f"\n[1/4] {t_default['step_scan']}")
    source_files = find_all_source_files()
    print(f"      {len(source_files)} {t_default['found_files']}")

    print(f"\n[2/4] {t_default['step_parse']}")
    all_funcs_count = 0
    nav_entries_by_lang = {lang: [] for lang in LANGUAGES}

    os.makedirs(OUTPUT_BASE, exist_ok=True)

    for src_file in source_files:
        funcs = parse_file(src_file)
        all_funcs_count += len(funcs)

        for lang in LANGUAGES:
            md_content, md_full_path, md_filename = generate_file_md(src_file, funcs, lang)
            with open(md_full_path, "w", encoding="utf-8") as f:
                f.write(md_content)
            nav_entries_by_lang[lang].append(f"      - '{src_file}': {md_filename}")

        print(f"      ✓ {t_default['processed']}: {src_file} ({len(funcs)} {t_default['funcs']})")

    print(f"\n[3/4] {t_default['step_index']}")
    for lang in LANGUAGES:
        t = I18N[lang]
        index_md = generate_index_md(len(source_files), all_funcs_count, lang)
        index_path = os.path.join(OUTPUT_BASE, f"api_{lang}.md")
        with open(index_path, "w", encoding="utf-8") as f:
            f.write(index_md)
        print(f"      ✓ api_{lang}.md ({t['nav_home']})")

        detail_path = generate_api_detail_html(lang)
        print(f"      ✓ software_design_detail_{lang}.html")

    main_html_path = generate_main_index_html()
    print(f"      ✓ docs/index.html (主首頁，預設英文，右上語系下拉)")

     # 將 docs/ 下所有 *_xx.md 轉換為自給自足的 HTML
    converted_html = convert_all_md_to_html()
    print(f"      ✓ {len(converted_html)} .md → .html 轉換完成")

    css_dir = os.path.join("docs", "stylesheets")
    os.makedirs(css_dir, exist_ok=True)
    css_content = """/* PDF 列印模式專屬設定 */
@media print {
    .no-print {
        display: none !important;
    }
    .page-break {
        page-break-before: always !important;
        break-before: page !important;
    }
    img {
        max-width: 100% !important;
        max-height: 150mm !important;
        object-fit: contain !important;
        page-break-inside: avoid !important;
        break-inside: avoid !important;
        display: block;
        margin: 0 auto;
    }
    table {
        page-break-inside: avoid !important;
        break-inside: avoid !important;
    }
}
"""
    with open(os.path.join(css_dir, "extra.css"), "w", encoding="utf-8") as f:
        f.write(css_content)

    print(f"\n[4/4] {t_default['step_mkdocs']}")
    nav_blocks = []
    for lang in LANGUAGES:
        t = I18N[lang]
        nav_yaml_block = "\n".join(nav_entries_by_lang[lang])
        nav_blocks.append(f"""  - {t['nav_home']} ({lang.upper()}): 03_software_detailed_design/api/api_{lang}.md
  - {t['nav_source_structure']} ({lang.upper()}):
{nav_yaml_block}""")

    all_nav = "\n".join(nav_blocks)

    mkdocs_content = f'''site_name: TRAE Test Project Documentation
site_description: ASPICE SWE.3 API Reference for the TRAE test project
site_author: Steven.Yang

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - with-pdf:
      output_path: trae_test_documentation.pdf
      cover_title: "TRAE Test Project - API Reference"
      cover_subtitle: "ASPICE SWE.3 Auto-Generated Documentation"
      author: "Steven.Yang"
      toc_title: "{t_default['toc_title']}"

nav:
{all_nav}
'''
    with open("mkdocs.yml", "w", encoding="utf-8") as f:
        f.write(mkdocs_content)
    print("      ✓ mkdocs.yml")

    print("\n" + "=" * 60)
    print(f"{t_default['done']} {OUTPUT_BASE}/")
    print("=" * 60)

if __name__ == "__main__":
    main()