#!/usr/bin/env python3
import os
import re
import subprocess
import base64
import uuid
from datetime import datetime
from pathlib import Path

# ==========================================
# 輸出路徑 (ASPICE SWE.3 附屬 API 參考文件)
# ==========================================
OUTPUT_BASE = os.path.join("docs", "03_software_detailed_design", "api")
LANGUAGES = ["en", "cn", "tw"]

# ==========================================
# 多語系翻譯字典
# ==========================================
I18N = {
    "en": {
        "project_title": "IRQ Simulator - Auto-Generated API Reference",
        "project_overview": "This is a C language embedded project developed with TRAE IDE, featuring interrupt handling and GitLab CI/CD integration.",
        "total_files_scanned": "Total source files scanned: {total_files}, {total_funcs} function definitions extracted.",
        "doc_generated_time": "Document Generated At",
        "module_arch_diagram": "Module Architecture Diagram",
        "file_path_label": "File Path",
        "no_funcs_found": "No functions with matching Doxygen comments found in this file.",
        "item": "Item",
        "description": "Description",
        "brief_label": "Brief",
        "no_brief": "No description",
        "params_label": "Parameters",
        "none": "None",
        "retval_label": "Return Value",
        "retval_void": "None (void)",
        "remark_label": "Remark",
        "exec_flow": "Execution Flow Diagram",
        "pdf_download": "PDF Download",
        "pdf_desc": "PDF Document (includes full architecture and source code documentation)",
        "pdf_link_text": "Download Complete Documentation (PDF)",
        "auto_generated_footer": "This document is auto-generated by GitLab CI from source code.",
        "nav_home": "Overview",
        "nav_source_structure": "Source Code Structure",
        "toc_title": "Table of Contents",
        "arch_reset_entry": "Reset Entry",
        "arch_main_func": "main Function",
        "arch_reg_handlers": "Register ISR Handlers",
        "arch_main_loop": "Main Loop",
        "arch_tick_isr": "Tick ISR",
        "arch_ext_isr": "External ISR",
        "arch_tick_check": "tick handler set?",
        "arch_int_check": "int handler set?",
        "arch_yes": "Yes",
        "arch_set": "Set",
        "flow_start": "Start",
        "flow_init": "Initialize ISR Pointers",
        "flow_reg_tick": "Set _rom_except_tick",
        "flow_reg_int": "Set _rom_except_int",
        "flow_print": "Print Welcome Message",
        "flow_loop": "Enter Main Loop",
        "flow_tick_trigger": "Tick IRQ Triggered",
        "flow_inc_tick": "Increment tick_count",
        "flow_return": "Return",
        "flow_exc_trigger": "Exception IRQ Triggered",
        "flow_inc_exc": "Increment exception_count",
        "flow_main": "main Execution Flow",
        "flow_tick": "tick_irq_handler Execution Flow",
        "flow_exc": "exception_irq_handler Execution Flow",
        "banner": "TRAE Project Auto-Documentation Generator (ASPICE SWE.3 API Reference)",
        "step_scan": "Searching for all .c and .h files...",
        "step_parse": "Parsing source code and rendering diagrams via mmdc...",
        "step_index": "Generating language-specific index pages and print CSS...",
        "step_mkdocs": "Generating mkdocs.yml...",
        "found_files": "source files found",
        "processed": "Processed",
        "funcs": "functions",
        "done": "Documentation generation complete! Output:",
        "warn_mermaid": "Mermaid conversion failed",
    },
    "cn": {
        "project_title": "IRQ Simulator - 自动生成 API 参考文件",
        "project_overview": "这是一个使用 TRAE IDE 开发的 C 语言嵌入式项目，包含中断处理功能和 GitLab CI/CD 集成。",
        "total_files_scanned": "共扫描 {total_files} 个源代码文件，提取出 {total_funcs} 个函数定义。",
        "doc_generated_time": "文件生成时间",
        "module_arch_diagram": "模块架构图",
        "file_path_label": "文件路径",
        "no_funcs_found": "此文件目前没有解析到符合格式的函数注释。",
        "item": "项目",
        "description": "说明",
        "brief_label": "功能说明",
        "no_brief": "无特别说明",
        "params_label": "参数说明",
        "none": "无",
        "retval_label": "返回值",
        "retval_void": "无 (void)",
        "remark_label": "备注",
        "exec_flow": "执行流程图",
        "pdf_download": "PDF 下载",
        "pdf_desc": "PDF 文件 (包含完整架构与源代码说明)",
        "pdf_link_text": "下载完整说明文件 (PDF)",
        "auto_generated_footer": "本文件由 GitLab CI 自动扫描源代码并生成。",
        "nav_home": "概述",
        "nav_source_structure": "源代码结构",
        "toc_title": "目录",
        "arch_reset_entry": "重置入口",
        "arch_main_func": "main 函数",
        "arch_reg_handlers": "注册中断处理器",
        "arch_main_loop": "主循环",
        "arch_tick_isr": "Tick 中断",
        "arch_ext_isr": "外部中断",
        "arch_tick_check": "tick 处理器已设置?",
        "arch_int_check": "int 处理器已设置?",
        "arch_yes": "是",
        "arch_set": "设置",
        "flow_start": "开始",
        "flow_init": "初始化中断处理器指针",
        "flow_reg_tick": "设置 _rom_except_tick",
        "flow_reg_int": "设置 _rom_except_int",
        "flow_print": "打印欢迎信息",
        "flow_loop": "进入主循环",
        "flow_tick_trigger": "Tick IRQ 触发",
        "flow_inc_tick": "增加 tick_count",
        "flow_return": "返回",
        "flow_exc_trigger": "Exception IRQ 触发",
        "flow_inc_exc": "增加 exception_count",
        "flow_main": "main 执行流程图",
        "flow_tick": "tick_irq_handler 执行流程图",
        "flow_exc": "exception_irq_handler 执行流程图",
        "banner": "TRAE 项目自动文档生成器 (ASPICE SWE.3 API 参考)",
        "step_scan": "正在搜索所有 .c 和 .h 文件...",
        "step_parse": "正在解析源代码并调用 mmdc 渲染图表...",
        "step_index": "正在生成各语言首页与打印 CSS...",
        "step_mkdocs": "正在生成 mkdocs.yml...",
        "found_files": "个源代码文件",
        "processed": "处理完成",
        "funcs": "个函数",
        "done": "文档生成完成！输出目录：",
        "warn_mermaid": "Mermaid 转换失败",
    },
    "tw": {
        "project_title": "IRQ Simulator - 自動生成 API 參考文件",
        "project_overview": "這是一個使用 TRAE IDE 開發的 C 語言嵌入式專案，包含中斷處理功能和 GitLab CI/CD 整合。",
        "total_files_scanned": "總共掃描到 {total_files} 個原始碼檔案，擷取出 {total_funcs} 個函式定義。",
        "doc_generated_time": "文件產生時間",
        "module_arch_diagram": "模組架構圖",
        "file_path_label": "檔案路徑",
        "no_funcs_found": "此檔案目前沒有解析到符合格式的函式註解。",
        "item": "項目",
        "description": "說明",
        "brief_label": "功能說明",
        "no_brief": "無特別說明",
        "params_label": "參數說明",
        "none": "無",
        "retval_label": "回傳值",
        "retval_void": "無 (void)",
        "remark_label": "備註",
        "exec_flow": "執行流程圖",
        "pdf_download": "PDF 下載",
        "pdf_desc": "PDF 文件 (包含完整架構與原始碼說明)",
        "pdf_link_text": "下載完整說明文件 (PDF)",
        "auto_generated_footer": "本文件由 GitLab CI 自動掃描原始碼並產生。",
        "nav_home": "概述",
        "nav_source_structure": "原始碼結構",
        "toc_title": "目錄",
        "arch_reset_entry": "重置入口",
        "arch_main_func": "main 函式",
        "arch_reg_handlers": "註冊中斷處理器",
        "arch_main_loop": "主迴圈",
        "arch_tick_isr": "Tick 中斷",
        "arch_ext_isr": "外部中斷",
        "arch_tick_check": "tick 處理器已設定?",
        "arch_int_check": "int 處理器已設定?",
        "arch_yes": "是",
        "arch_set": "設定",
        "flow_start": "開始",
        "flow_init": "初始化中斷處理器指標",
        "flow_reg_tick": "設定 _rom_except_tick",
        "flow_reg_int": "設定 _rom_except_int",
        "flow_print": "列印歡迎訊息",
        "flow_loop": "進入主迴圈",
        "flow_tick_trigger": "Tick IRQ 觸發",
        "flow_inc_tick": "增加 tick_count",
        "flow_return": "返回",
        "flow_exc_trigger": "Exception IRQ 觸發",
        "flow_inc_exc": "增加 exception_count",
        "flow_main": "main 執行流程圖",
        "flow_tick": "tick_irq_handler 執行流程圖",
        "flow_exc": "exception_irq_handler 執行流程圖",
        "banner": "TRAE 專案自動文件產生器 (ASPICE SWE.3 API 參考)",
        "step_scan": "正在搜尋所有 .c 和 .h 檔案...",
        "step_parse": "正在解析原始碼並呼叫 mmdc 渲染圖表...",
        "step_index": "正在產生各語言首頁與列印 CSS...",
        "step_mkdocs": "正在產生 mkdocs.yml...",
        "found_files": "個原始碼檔案",
        "processed": "處理完成",
        "funcs": "個函式",
        "done": "文件產生完成！輸出目錄：",
        "warn_mermaid": "Mermaid 轉換失敗",
    },
}

# ==========================================
# Mermaid 轉換核心引擎 (PNG 轉 Base64)
# ==========================================
def create_puppeteer_config():
    config_path = "puppeteer-config.json"
    if not os.path.exists(config_path):
        with open(config_path, "w", encoding="utf-8") as f:
            f.write('{"args": ["--no-sandbox", "--disable-setuid-sandbox"]}')
    return config_path

def render_mermaid_to_png_base64(mermaid_code, alt_text, lang="tw"):
    config_path = create_puppeteer_config()
    unique_id = uuid.uuid4().hex
    temp_mmd = f"temp_{unique_id}.mmd"
    temp_png = f"temp_{unique_id}.png"

    with open(temp_mmd, "w", encoding="utf-8") as f:
        f.write(mermaid_code)

    try:
        subprocess.run([
            "mmdc",
            "-i", temp_mmd,
            "-o", temp_png,
            "-p", config_path,
            "-b", "white",
            "-s", "2"
        ], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        with open(temp_png, "rb") as f:
            encoded = base64.b64encode(f.read()).decode('utf-8')

        return f"![{alt_text}](data:image/png;base64,{encoded})"
    except subprocess.CalledProcessError as e:
        t = I18N.get(lang, I18N["tw"])
        print(f"      [{t['warn_mermaid']}]: {e.stderr.decode('utf-8', errors='ignore')}")
        return f"""```mermaid
{mermaid_code}
```"""
    finally:
        if os.path.exists(temp_mmd):
            os.remove(temp_mmd)
        if os.path.exists(temp_png):
            os.remove(temp_png)

# ==========================================
# 專案原始碼解析
# ==========================================
def find_all_source_files():
    source_files = []
    for filepath in Path(".").rglob("*.[ch]"):
        path_str = str(filepath)
        if "build" not in path_str and "docs" not in path_str:
            source_files.append(path_str)
    return sorted(source_files)

def parse_file(filepath):
    if not os.path.exists(filepath):
        return []

    funcs = []
    in_comment = False
    current_comment = []

    with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    for i, line in enumerate(lines):
        if "/**" in line:
            in_comment = True
            current_comment = []
            continue

        if in_comment:
            if "*/" in line:
                in_comment = False
                continue
            current_comment.append(line.strip())
            continue

        func_pattern = r"^(?:(?:void|int|char|unsigned|short|long|static|inline)\s+)+(\w+)\s*\((.*?)\)"
        func_match = re.match(func_pattern, line.strip())

        if func_match and current_comment:
            func_name = func_match.group(1)
            func_params = func_match.group(2)

            brief = ""
            remark = ""
            params = []
            retval = ""

            for cline in current_comment:
                if "@brief" in cline:
                    brief = cline.split("@brief", 1)[1].strip(" :")
                if "@remark" in cline:
                    remark = cline.split("@remark", 1)[1].strip()
                if "@param" in cline:
                    params.append(cline.strip())
                if "@retval" in cline:
                    retval = cline.strip()

            funcs.append({
                "name": func_name,
                "brief": brief,
                "remark": remark,
                "doc_params": params,
                "doc_retval": retval
            })
            current_comment = []

    return funcs

# ==========================================
# 多語系 Markdown 與圖表生成
# ==========================================
def generate_mermaid_arch(lang):
    t = I18N[lang]
    code = f"""graph TD
    A[start.s<br/>{t['arch_reset_entry']}] --> B[_except_reset]
    B --> C[main.c<br/>{t['arch_main_func']}]
    C --> D[{t['arch_reg_handlers']}]
    D --> E[{t['arch_main_loop']}]

    F[_tick_isr<br/>{t['arch_tick_isr']}] --> G{{{t['arch_tick_check']}}}
    G -->|{t['arch_yes']}| H[tick_irq_handler]

    I[_int_isr<br/>{t['arch_ext_isr']}] --> J{{{t['arch_int_check']}}}
    J -->|{t['arch_yes']}| K[exception_irq_handler]

    C -.->|{t['arch_set']}| G
    C -.->|{t['arch_set']}| J
"""
    return render_mermaid_to_png_base64(code, t['module_arch_diagram'], lang)

def generate_function_flow_diagram(func_name, lang):
    t = I18N[lang]
    diagrams = {
        "main": (
            f"""flowchart TD
    Start([{t['flow_start']}]) --> Init[{t['flow_init']}]
    Init --> RegTick[{t['flow_reg_tick']}]
    RegTick --> RegInt[{t['flow_reg_int']}]
    RegInt --> Print1[{t['flow_print']}]
    Print1 --> Loop[{t['flow_loop']}]
    Loop --> Loop
""",
            t['flow_main']
        ),
        "tick_irq_handler": (
            f"""flowchart TD
    Start([{t['flow_tick_trigger']}]) --> Inc[{t['flow_inc_tick']}]
    Inc --> End([{t['flow_return']}])
""",
            t['flow_tick']
        ),
        "exception_irq_handler": (
            f"""flowchart TD
    Start([{t['flow_exc_trigger']}]) --> Inc[{t['flow_inc_exc']}]
    Inc --> End([{t['flow_return']}])
""",
            t['flow_exc']
        ),
    }

    if func_name not in diagrams:
        return ""

    code, alt = diagrams[func_name]
    return render_mermaid_to_png_base64(code, alt, lang)

def generate_index_md(total_files, total_funcs, lang):
    t = I18N[lang]
    content = f"""# {t['project_title']}

**{t['doc_generated_time']}**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## {t['nav_home']}

{t['project_overview']}
{t['total_files_scanned'].format(total_files=total_files, total_funcs=total_funcs)}

---

## {t['module_arch_diagram']}

{generate_mermaid_arch(lang)}

---

<div class="no-print">
<h2>{t['pdf_download']}</h2>
<h3>📄 {t['pdf_desc']}</h3>
<p><a href="../../trae_test_documentation.pdf">📥 {t['pdf_link_text']}</a></p>
<hr>
</div>

*{t['auto_generated_footer']}*
"""
    return content

def generate_file_md(filepath, funcs, lang):
    t = I18N[lang]
    safe_name = filepath.replace("\\", "/").replace(".", "_")
    md_filename = f"{safe_name}_{lang}.md"
    md_full_path = os.path.join(OUTPUT_BASE, md_filename)
    os.makedirs(os.path.dirname(md_full_path), exist_ok=True)

    filename = os.path.basename(filepath)
    is_header_file = filepath.lower().endswith(".h")

    content = f"# {filename}\n\n**{t['file_path_label']}**: `{filepath}`\n\n---\n\n"

    if not funcs:
        content += f"> *{t['no_funcs_found']}*\n"
        return content, md_full_path, md_filename

    for f in funcs:
        content += "\n<div class=\"page-break\"></div>\n\n"
        content += f"### {f['name']}\n\n"

        content += f"| {t['item']} | {t['description']} |\n"
        content += "| :--- | :--- |\n"

        brief_text = f['brief'] if f['brief'] else t['no_brief']
        content += f"| **{t['brief_label']}** | {brief_text} |\n"

        if f['doc_params']:
            params_html = "<br>".join([f"• {p}" for p in f['doc_params']])
            content += f"| **{t['params_label']}** | {params_html} |\n"
        else:
            content += f"| **{t['params_label']}** | {t['none']} |\n"

        if f['doc_retval']:
            content += f"| **{t['retval_label']}** | {f['doc_retval']} |\n"
        else:
            content += f"| **{t['retval_label']}** | {t['retval_void']} |\n"

        if f['remark']:
            content += f"| **{t['remark_label']}** | {f['remark']} |\n"

        content += "\n\n"

        if not is_header_file:
            flow_diag = generate_function_flow_diagram(f['name'], lang)
            if flow_diag:
                content += f"**{t['exec_flow']}**:\n\n"
                content += flow_diag + "\n\n"

        content += "---\n\n"

    return content, md_full_path, md_filename

# ==========================================
# 主程式
# ==========================================
def main():
    t_default = I18N["tw"]
    print("=" * 60)
    print(t_default['banner'])
    print("=" * 60)

    print(f"\n[1/4] {t_default['step_scan']}")
    source_files = find_all_source_files()
    print(f"      {len(source_files)} {t_default['found_files']}")

    print(f"\n[2/4] {t_default['step_parse']}")
    all_funcs_count = 0
    nav_entries_by_lang = {lang: [] for lang in LANGUAGES}

    os.makedirs(OUTPUT_BASE, exist_ok=True)

    for src_file in source_files:
        funcs = parse_file(src_file)
        all_funcs_count += len(funcs)

        for lang in LANGUAGES:
            md_content, md_full_path, md_filename = generate_file_md(src_file, funcs, lang)
            with open(md_full_path, "w", encoding="utf-8") as f:
                f.write(md_content)
            nav_entries_by_lang[lang].append(f"      - '{src_file}': {md_filename}")

        print(f"      ✓ {t_default['processed']}: {src_file} ({len(funcs)} {t_default['funcs']})")

    print(f"\n[3/4] {t_default['step_index']}")
    for lang in LANGUAGES:
        t = I18N[lang]
        index_md = generate_index_md(len(source_files), all_funcs_count, lang)
        index_path = os.path.join(OUTPUT_BASE, f"index_{lang}.md")
        with open(index_path, "w", encoding="utf-8") as f:
            f.write(index_md)
        print(f"      ✓ index_{lang}.md ({t['nav_home']})")

    css_dir = os.path.join("docs", "stylesheets")
    os.makedirs(css_dir, exist_ok=True)
    css_content = """/* PDF 列印模式專屬設定 */
@media print {
    .no-print {
        display: none !important;
    }
    .page-break {
        page-break-before: always !important;
        break-before: page !important;
    }
    img {
        max-width: 100% !important;
        max-height: 150mm !important;
        object-fit: contain !important;
        page-break-inside: avoid !important;
        break-inside: avoid !important;
        display: block;
        margin: 0 auto;
    }
    table {
        page-break-inside: avoid !important;
        break-inside: avoid !important;
    }
}
"""
    with open(os.path.join(css_dir, "extra.css"), "w", encoding="utf-8") as f:
        f.write(css_content)

    print(f"\n[4/4] {t_default['step_mkdocs']}")
    nav_blocks = []
    for lang in LANGUAGES:
        t = I18N[lang]
        nav_yaml_block = "\n".join(nav_entries_by_lang[lang])
        nav_blocks.append(f"""  - {t['nav_home']} ({lang.upper()}): 03_software_detailed_design/api/index_{lang}.md
  - {t['nav_source_structure']} ({lang.upper()}):
{nav_yaml_block}""")

    all_nav = "\n".join(nav_blocks)

    mkdocs_content = f'''site_name: TRAE Test Project Documentation
site_description: ASPICE SWE.3 API Reference for the TRAE test project
site_author: Steven.Yang

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - with-pdf:
      output_path: trae_test_documentation.pdf
      cover_title: "TRAE Test Project - API Reference"
      cover_subtitle: "ASPICE SWE.3 Auto-Generated Documentation"
      author: "Steven.Yang"
      toc_title: "{t_default['toc_title']}"

nav:
{all_nav}
'''
    with open("mkdocs.yml", "w", encoding="utf-8") as f:
        f.write(mkdocs_content)
    print("      ✓ mkdocs.yml")

    print("\n" + "=" * 60)
    print(f"{t_default['done']} {OUTPUT_BASE}/")
    print("=" * 60)

if __name__ == "__main__":
    main()